### ISSUE TITLE
"cilp" is unstable running！

### ISSUE THREAD

**Issue by lujieha** [paulmach/orb#20]
Hello, Paul Mach
This project is very good and it gives me a lot of help at work. I am currently cutting Geojson using "clip". I see an unstable situation with "clip": the result of calculating the output in the same data is not.
Codes：

```
        fc,err:=geojson.UnmarshalFeatureCollection(b)
	mset:=maptile.Set{}
	for i:=range fc.Features{
		ms:=tilecover.Geometry(fc.Features[i].Geometry,11)
		for k,_:=range ms{
			mset[k]=true
			cps:=clip.Geometry(k.Bound().Bound(),fc.Features[i].Geometry)
			if cps!=nil{
				fmt.Println(k,len(cps.(orb.Polygon)[0]))
			}else
                        {
				fmt.Println(k,"clip error")
			}

		}
	}
	fmt.Println(len(mset))
```

-------------------------------
After running multiple times, sometimes output:
_{1684 850 11} 5
{1685 851 11} 7
{1685 850 11} 9
3
Sometimes output:
{1684 850 11} 5
{1685 851 11} 7
{1685 850 11} error
3_
thank you very much!
GeoJson:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              116.22367858886719,
              29.165353121242656
            ],
            [
              116.18453979492186,
              29.136568744954467
            ],
            [
              116.16874694824217,
              29.11917427664377
            ],
            [
              116.19483947753906,
              29.07837571206272
            ],
            [
              116.20101928710936,
              29.045965338037213
            ],
            [
              116.21406555175781,
              29.019549354428978
            ],
            [
              116.24015808105469,
              29.003936732742975
            ],
            [
              116.32530212402342,
              29.010542360621983
            ],
            [
              116.36032104492186,
              29.02555358063341
            ],
            [
              116.36581420898438,
              29.062771988976138
            ],
            [
              116.3294219970703,
              29.09997696628295
            ],
            [
              116.26281738281249,
              29.162954731306638
            ],
            [
              116.22367858886719,
              29.165353121242656
            ]
          ]
        ]
      }
    }
  ]
}
```

**Comment by paulmach** [comment]
I think the core issue is that `clip.Geometry` modifies the original geometry/memory. This is by design to allow the user to decide if they need a reallocation or not.

If you need a reallocation try something like:
`cps:=clip.Geometry(k.Bound(),orb.Clone(fc.Features[i].Geometry))`

If you don't need a reallocation you need to update the feature's geometry with the the new value like:
`fc.Features[i].Geometry:=clip.Geometry(k.Bound(),fc.Features[i].Geometry)`

In this second case you will always get `nil` because you're clipping out all the tiles the cover the geometry, e.g. you're clipping everything out, so there is nothing.
