### ISSUE TITLE
Generate multiple tiles from same GeoJSON FeatureCollections

### ISSUE THREAD

**Issue by DerZade** [paulmach/orb#46]
Okay, I'm kind of new to Go so sorry if this a dumb question, but I ran into some difficulties when creating more than just one mvt from multiple GeoJSON FeatureCollections.
I would argue that it's a fairly standard thing users would do, because no one will just generate a single tile and be done.

The example in the README looks like this:
```go
// Start with a set of feature collections defining each layer in lon/lat (WGS84).
collections := map[string]*geojson.FeatureCollection{}

// Convert to a layers object and project to tile coordinates.
layers := mvt.NewLayers(collections)
layers.ProjectToTile(maptile.New(x, y, z))

// encoding using the Mapbox Vector Tile protobuf encoding.
data, err := layers.MarshalGzipped()
```

But if you want to create multiple tiles from the same layers this misses a crucial step. Before projecting the layers to a new tile you now have to project the layers back to WGS84 with `layers.ProjectToWGS84` (took me way to long to figure that out so it would be nice to have a short paragraph in the README that explains that) 
Is that the intended way or is there another way to generate multiple files from the same GeoJSON FeatureCollections?

If that is the intended way I want to illustrate, why this workflow is far from optimal:
The root of the problem is that the projection seems to work completely in-place, which means in the example above using `ProjectToTile` changes even the coordinates of the features in the `collections`-map. Imho projecting the Layers shouldn't change the original data or there should at least be a disclaimer that this is the case.

This "everything in-place" approach basically prevents any multi-threading when generating MVTs, which is imho ideal.

The other problem is that the projection is not 100% accurate (which is acceptable), but this means if I'm working with same Layers to generate multiple tiles the coordinates change ever so slightly every time I project from WGS84 to a tile and then back. So if I'm generating for example LODs 0 through 8 the coordinates on LOD 0 will be spot on but will be inaccurate on LOD 8, because at the point the first LOD 8 tile is being generated we already projected 43690 (2 * 21845) times and before the last time we projected 174761 times.

**Comment by paulmach** [comment]
I think the `1 collection -> multiple tiles` is the wrong approach.  With the workflow you describe above every tile will have the **full** collection.

Another workflow is `1 -> collection -> multiple collections each clipped for a tile -> project -> make tiles`.  This favors the "project in place" approach because you're not copying a potentially still large clipped geojson collections.

So how would you do this using `orb`.  Haven't used it (and go) in a while, but I did get something similar to work a while back so all the pieces should be here. You can look at the [smartclip](https://github.com/paulmach/orb/blob/master/clip/smartclip/smart.go), maptile and tilecover subpackages.

Then do something like
```
tiles = tilecover.Covering(bounds of the full collections)
for tile range tiles {
  bound = tile.Bound(0.5)
  // smart clip all the geometry in the collection to a new collection

  // then similar to above
  layers := mvt.NewLayers(collections)
  layers.ProjectToTile(tile)

  // encoding using the Mapbox Vector Tile protobuf encoding.
  data, err := layers.MarshalGzipped()
}
```

I hope that helps and wasn't just rambling...  

Alternately you can use something like [tippecanoe](https://github.com/mapbox/tippecanoe) which is a much more optimzed command line tool that'll convert geojson -> mvt.

**Comment by DerZade** [comment]
Thanks a lot for the quick response. I'll try it out.
